services:
  app:
    build: .
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - carmen_network
    env_file:
      - .env
    restart: always

networks:
  carmen_network:
    external: true
