export interface Trupe {
  nome: string;
  sexo: "Masculino" | "Feminino";
  hobby: "Tenis" | "Basquete" | "Alpinismo" | "Futebol";
  cabelo: "Loiro" | "Ruivo" | "Castanho" | "Preto";
  caracteristica: "Joias" | "Tatuagem" | "Cicatriz" | "Óculos";
  veiculo: "Limousine" | "Conversivel" | "Moto" | "Jipe";
  imagem: string;
  idade: string;
  outro: string;
}

export const trupeiros: Trupe[] = [
  {
    nome: "Chrolliguin",
    sexo: "Masculino",
    idade: "24 ANOS",
    hobby: "Tenis",
    cabelo: "Preto",
    veiculo: "Moto",
    caracteristica: "Cicatriz",
    outro: "Apaixonado por Arte",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Chrolliguin",
  },
  {
    nome: "Pedronaga",
    sexo: "Masculino",
    idade: "31 ANOS",
    hobby: "Basquete",
    cabelo: "Preto",
    caracteristica: "Óculos",
    veiculo: "Limousine",
    outro: "Perito na arte da Katana",
    imagem: "https://i.pinimg.com/736x/21/53/b7/2153b7548b260de8f5ed1ff1400dc949.jpg",
  },
  {
    nome: "Ferinhatan",
    sexo: "Masculino",
    idade: "28 ANOS",
    hobby: "Alpinismo",
    cabelo: "Preto",
    caracteristica: "Joias",
    veiculo: "Conversivel",
    outro: "Astuto e muito ganancioso",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Ferinhatan",
  },
  {
    nome: "Biamachi",
    sexo: "Feminino",
    idade: "22 ANOS",
    hobby: "Futebol",
    cabelo: "Ruivo",
    caracteristica: "Tatuagem",
    veiculo: "Jipe",
    outro: "Costura com precisão cirúrgica",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Biamachi",
  },
  {
    nome: "Hisokami",
    sexo: "Feminino",
    idade: "29 ANOS",
    hobby: "Futebol",
    cabelo: "Ruivo",
    caracteristica: "Cicatriz",
    veiculo: "Limousine",
    outro: "Mestra das cartas ilusórias",
    imagem: "https://i.pinimg.com/736x/32/19/22/321922c159bf4070a927a42a0335e8cf.jpg",
  },
  {
    nome: "Jaguatiphinks",
    sexo: "Masculino",
    idade: "33 ANOS",
    hobby: "Tenis",
    cabelo: "Loiro",
    caracteristica: "Joias",
    veiculo: "Moto",
    outro: "Usa casacos esportivos sempre",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Jaguatiphinks",
  },
  {
    nome: "Jonark",
    sexo: "Masculino",
    idade: "25 ANOS",
    hobby: "Alpinismo",
    cabelo: "Loiro",
    caracteristica: "Óculos",
    veiculo: "Moto",
    outro: "Trabalha guiando grupos nas montanhas",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Jonark",
  },
  {
    nome: "Franklin",
    sexo: "Masculino",
    idade: "42 ANOS",
    hobby: "Futebol",
    cabelo: "Ruivo",
    caracteristica: "Joias",
    veiculo: "Conversivel",
    outro: "Carga pesada e porte assustador",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Franklin",
  },
  {
    nome: "Noshizuko",
    sexo: "Masculino",
    idade: "20 ANOS",
    hobby: "Alpinismo",
    cabelo: "Preto",
    caracteristica: "Joias",
    veiculo: "Limousine",
    outro: "Mora em porões de leilões clandestinos",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Noshizuko",
  },
  {
    nome: "skye",
    sexo: "Feminino",
    idade: "21 ANOS",
    hobby: "Futebol",
    cabelo: "Preto",
    caracteristica: "Óculos",
    veiculo: "Jipe",
    outro: "Mente afiada para interrogar",
    imagem: "https://i.pinimg.com/736x/5d/76/89/5d7689d0db3b42ee86f1e1eb84ef03ef.jpg",
  },
  {
    nome: "Kalangolenof",
    sexo: "Masculino",
    idade: "36 ANOS",
    hobby: "Basquete",
    cabelo: "Castanho",
    caracteristica: "Tatuagem",
    veiculo: "Jipe",
    outro: "Tem um som estranho na voz",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Kalangolenof",
  },
  {
    nome: "Ulobin",
    sexo: "Masculino",
    idade: "30 ANOS",
    hobby: "Alpinismo",
    cabelo: "Ruivo",
    caracteristica: "Óculos",
    veiculo: "Moto",
    outro: "Grita como um leão assustador",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Ulobin",
  },
  {
    nome: "Weskortopi",
    sexo: "Masculino",
    idade: "19 ANOS",
    hobby: "Basquete",
    cabelo: "Castanho",
    caracteristica: "Tatuagem",
    veiculo: "Jipe",
    outro: "Coleciona objetos miniatura",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=Weskortopi",
  },
  {
    nome: "Carmen Sandiego trupe",
    sexo: "Feminino",
    idade: "99 ANOS",
    hobby: "Tenis",
    cabelo: "Ruivo",
    caracteristica: "Joias",
    veiculo: "Conversivel",
    outro: "Pessoa misteriosa, nunca foi vista.",
    imagem: "https://api.dicebear.com/7.x/pixel-art/svg?seed=CarmenSandiego",
  },
];
