export interface Trupe {
  nome: string;
  sexo: "Masculino" | "Feminino";
  hobby: "Tenis" | "Basquete" | "Alpinismo" | "Futebol";
  cabelo: "Loiro" | "Ruivo" | "Castanho" | "Preto";
  caracteristica: "Joias" | "Tatuagem" | "Cicatriz" | "Óculos";
  veiculo: "Limousine" | "Conversivel" | "Moto" | "Jipe";
  imagem: string;
  idade: string;
  outro: string;
  alias?: string;
}

export const trupeiros: Trupe[] = [
  {
    nome: "Chrolliguin",
    sexo: "Masculino",
    idade: "24 ANOS",
    hobby: "Tenis",
    cabelo: "Preto",
    veiculo: "Moto",
    caracteristica: "Cicatriz",
    outro: "Apaixonado por Arte",
    imagem: "https://qph.cf2.quoracdn.net/main-qimg-9eab730c82f42a399a5002235b5e491e-lq",
  },
  {
    nome: "Pedronaga",
    sexo: "Masculino",
    idade: "31 ANOS",
    hobby: "Basquete",
    cabelo: "Preto",
    caracteristica: "Óculos",
    veiculo: "Limousine",
    outro: "Perito na arte da Katana",
    imagem: "/assets/trupe/pedronaga.png",
  },
  {
    nome: "Ferinhatan",
    sexo: "Masculino",
    idade: "28 ANOS",
    hobby: "Alpinismo",
    cabelo: "Preto",
    caracteristica: "Joias",
    veiculo: "Conversivel",
    outro: "Astuto e muito ganancioso",
    imagem: "https://64.media.tumblr.com/60a18d42b6284e2af17fdc7a8676fd74/b74e2331fa27026d-59/s250x400/f5025b37f5cc1074cc64d74bf76b6a931070a3bf.jpg",
  },
  {
    nome: "Biamachi",
    sexo: "Feminino",
    idade: "22 ANOS",
    hobby: "Futebol",
    cabelo: "Ruivo",
    caracteristica: "Tatuagem",
    veiculo: "Jipe",
    outro: "Costura com precisão cirúrgica",
    imagem: "https://64.media.tumblr.com/37375c459d91d245206f47f3f294d7cc/43407584080930c6-6c/s500x750/d3ae64dde267e5d4d4ede2d099d7ebeea63f2151.jpg",
  },
  {
    nome: "Hisokami",
    sexo: "Feminino",
    idade: "29 ANOS",
    hobby: "Futebol",
    cabelo: "Ruivo",
    caracteristica: "Cicatriz",
    veiculo: "Limousine",
    outro: "Mestra das cartas ilusórias",
    imagem: "/assets/trupe/hisokami.png",
  },
  {
    nome: "Jaguatiphinks",
    sexo: "Masculino",
    idade: "33 ANOS",
    hobby: "Tenis",
    cabelo: "Loiro",
    caracteristica: "Joias",
    veiculo: "Moto",
    outro: "Usa casacos esportivos sempre",
    imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyJNHb8L8HicHllFbwcFzp2JdVOJ7eO2tBuxDFRkTqJEQhfaN9R5NBMg-rC7Pmf4KkcQo&usqp=CAU",
  },
  {
    nome: "Jonark",
    sexo: "Masculino",
    idade: "25 ANOS",
    hobby: "Alpinismo",
    cabelo: "Loiro",
    caracteristica: "Óculos",
    veiculo: "Moto",
    outro: "Trabalha guiando grupos nas montanhas",
    imagem: "https://personality-index.com/images/profile/428d2b91-1926-4757-89a7-07d32f031d93.jpg",
  },
  {
    nome: "Franklin",
    sexo: "Masculino",
    idade: "42 ANOS",
    hobby: "Futebol",
    cabelo: "Ruivo",
    caracteristica: "Joias",
    veiculo: "Conversivel",
    outro: "Carga pesada e porte assustador",
    imagem: "https://cdn.personalitylist.com/avatars/7317.png",
  },
  {
    nome: "Noshizuko",
    sexo: "Masculino",
    idade: "20 ANOS",
    hobby: "Alpinismo",
    cabelo: "Preto",
    caracteristica: "Joias",
    veiculo: "Limousine",
    outro: "Mora em porões de leilões clandestinos",
    imagem: "https://64.media.tumblr.com/0aba7fda5f57484ba969ecd4b7115df2/42ebd1ec3c204215-52/s400x600/1dd3cf0aa37f5fab39aedc75d650f6d2867e783b.jpg",
  },
  {
    nome: "Pakunoda",
    sexo: "Feminino",
    idade: "28 ANOS",
    hobby: "Futebol",
    cabelo: "Loiro",
    caracteristica: "Óculos",
    veiculo: "Jipe",
    outro: "Mente afiada para interrogar",
    imagem: "https://i.pinimg.com/736x/f1/ef/e4/f1efe4e1efd2db2a503c9dcb7cb88352.jpg",
  },
  {
    nome: "skye",
    sexo: "Feminino",
    idade: "21 ANOS",
    hobby: "Futebol",
    cabelo: "Preto",
    caracteristica: "Óculos",
    veiculo: "Jipe",
    outro: "Mente afiada para interrogar",
    imagem: "/assets/trupe/skye.png",
  },
  {
    nome: "Kalangolenof",
    sexo: "Masculino",
    idade: "36 ANOS",
    hobby: "Basquete",
    cabelo: "Castanho",
    caracteristica: "Tatuagem",
    veiculo: "Jipe",
    outro: "Tem um som estranho na voice",
    imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIR6KRv1N7bTou1X1iOlgAL3f12WSAsAM0ARabzEXiowq52UkTJXk3Vgc8_WPa8P--vs4&usqp=CAU",
  },
  {
    nome: "Ulobin",
    sexo: "Masculino",
    idade: "30 ANOS",
    hobby: "Alpinismo",
    cabelo: "Ruivo",
    caracteristica: "Óculos",
    veiculo: "Moto",
    outro: "Grita como um leão assustador",
    imagem: "https://i.pinimg.com/736x/6e/01/ae/6e01aeb685970ef4d0ec30b71636bae5.jpg",
  },
  {
    nome: "Weskortopi",
    sexo: "Masculino",
    idade: "19 ANOS",
    hobby: "Basquete",
    cabelo: "Castanho",
    caracteristica: "Tatuagem",
    veiculo: "Jipe",
    outro: "Coleciona objetos miniatura",
    imagem: "https://pm1.aminoapps.com/7273/b3bb3927665063bad6820f6566f0ad17dd2e72d9r1-210-240v2_00.jpg",
  },
  {
    nome: "Carmen Sandiego trupe",
    sexo: "Feminino",
    idade: "99 ANOS",
    hobby: "Tenis",
    cabelo: "Ruivo",
    caracteristica: "Joias",
    veiculo: "Conversivel",
    outro: "Pessoa misteriosa, nunca foi vista.",
    imagem: "https://i1.sndcdn.com/artworks-000486152007-9aymou-t500x500.jpg",
  },
];
